---
resources:
- name: git-new-version
  type: git
  source:
    uri: https://github.com/95rade/concourse-tutorial.git
    branch: develop

- name: 30m-timer
  type: time
  source:
    interval: 30m

jobs:
- name: TVE-system-smoke-test
  public: true
  serial: true
  plan:
  - get: git-new-version
  - get: 30m-timer
    trigger: true
  - task: TVE-system-smoke-test
    file: git-new-version/tutorials/basic/task-hello-world/task_hello_world.yml

